### ISSUE TITLE
Do not `stringify` validation targets

### ISSUE THREAD

**Issue by usualoma** [honojs/validator#11]
Currently, the following tests fail, but I don't think this is the expected result. I think this is due to `stringify` in the following places.
https://github.com/honojs/validator/blob/main/src/index.ts#L157

```ts
  app.post(
    '/json',
    validation((v) => ({
      json: {
        'post.author.email': v.required,
      },
    })),
    (c) => {
      return c.text('Valid')
    }
  )

  it('Should return 400 response - JSON', async () => {
    const json = {}
    const req = new Request('http://localhost/json', {
      method: 'POST',
      body: JSON.stringify(json),
    })
    const res = await app.request(req)
    expect(res.status).toBe(400)
  })
```

I prefer not to change the type in validation, since "validated with a different type than the type of the value actually retrieved" can easily lead to security problems.

**Comment by yusukebe** [comment]
Hi @usualoma 

You are right. This a critcal bug. I'll fix this.

Thank you!
