### ISSUE TITLE
Bug: Validating body prevents it from being read in the route handler

### ISSUE THREAD

**Issue by ThatOneBro** [honojs/validator#7]
This is more of an issue related to the Web API.... As far as I can tell, calling any of the `Request` object body parsing functions prevents you from calling them again unless you clone them. See: https://github.com/node-fetch/node-fetch/issues/533

So after the validation is run and we have called the body parsing method, if you try to call the function again (eg. `const body = await c.req.json()`), you will receive the error: 
```
TypeError: Body already consumed.
    at InnerBody.consume (deno:ext/fetch/22_body.js:140:34)
    at consumeBody (deno:ext/fetch/22_body.js:240:35)
    at Request.json (deno:ext/fetch/22_body.js:313:30)
    ...
```

I think we could call `c.req.clone()` in the `validation` function, and this would still allow us to still call `.json()`, `.body()`, etc. in the route handlers. What do you think?

**Comment by yusukebe** [comment]
Hi! @ThatOneBro !

Thanks for the clear explanation. You are right! It should be cloned.

Fixed this bug in #9 . Will release soon.
